#!/bin/bash
realm list | grep active-directory
isJoined=$?

if [ $isJoined -ne 0 ]; then
    joined=n
    while [ $joined != "y" ]
    do
        realm join -v ad.tingle.family --user=Administrator
        echo "Was domain join successful? [yN]"
        read joined
    done
fi

cp /opt/tingle_server_setup/ntp.conf /etc/ntp.conf

# Clean up sss db
cp /opt/tingle_server_setup/sssd.conf /etc/sssd/sssd.conf
rm -rf /var/lib/sss/db/*
systemctl restart sssd

if [ $isJoined -ne 0 ]; then
    pam-auth-update
fi

cp /opt/tingle_server_setup/00-on-login /etc/update-motd.d/00-on-login
cp /opt/tingle_server_setup/pam_mount.conf.xml /etc/security/pam_mount.conf.xml
echo "Copied motd and pam mount"

echo "Adding ssh-auth user"
adduser --system ssh-auth-user

echo "Replace AuthorizedKeysCommand"
sed -i '/AuthorizedKeysCommand /c\AuthorizedKeysCommand /opt/tingleauth/fetch_authorized_keys.py' /etc/ssh/sshd_config
sed -i '/AuthorizedKeysCommandUser /c\AuthorizedKeysCommandUser ssh-auth-user' /etc/ssh/sshd_config
systemctl restart sshd

echo "Setup cron to automatically update package"
if grep -q "update_package.sh" /etc/crontab; then
  sed -i '/update_package.sh/c\0 0 * * * root /opt/tingleauth/update_package.sh' /etc/crontab
else
  echo "0 0 * * * root /opt/tingleauth/update_package.sh" >> /etc/crontab
fi
systemctl restart cron

echo "Cleaning up"
rm -rf /opt/tingle_server_setup

